kind: pipeline
name: default

steps:
  - name: deploy
    image: node:8.10-alpine
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
    commands:
      - npm install
      - npx serverless -- deploy
    when:
      event: push