pipeline:
  deploy-dev:
    image: node:8.10-alpine
    commands:
      - npx serverless -- deploy
    when:
      event: push

  deploy-staging:
    image: node:8.10-alpine
    commands:
      - npx serverless -- deploy -s staging
    when:
      event: push